[build]
  publish = "/"
  command = "node -e \"const fs=require('fs');const content=fs.readFileSync('index.html','utf8');fs.writeFileSync('index.html',content.replace(/\\[([^\\]]+)\\]/g,(m,v)=>process.env[v]||m))\""

[build.processing]
  skip_processing = true

[build.environment]
  NODE_VERSION = "18"

[context.production]
  environment = { }  # Environment variables are set in Netlify UI

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
